//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryPractice.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialWarehouse
    {
        public int Id { get; set; }
        public int Material_Id { get; set; }
        public int Warehouse_Id { get; set; }
        public int Count { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
